### PR TITLE
AOC Day 23 Part 1

### PR DESCRIPTION
**Pull request by IsaacFleetwood**
I got the solution for Day 23 Part 1 down to 800ms from the 40s that it originally took. Aswell, the large puzzle input (141x141 grid) was able to be ran and completed (albeit in 17 minutes).

The way i did this was remove large nested loops with filters and instead create objects that then are accessed via an index (thereby making the access constant time versus O(n), making the state transition function O(n) instead of O(n^2). The overall timespan then is O(n^2) instead of O(n^3)). This is much faster, and I can't see much other room for improvement in the code itself, outside of a different solution entirely. However, 800ms, while usable, is still not exactly ideal, and if we have time, we would likely want to look into optimizing it in the future, if deemed appropriate.

### CODE REVIEW

**Comment by TiarkRompf** [comment]
Cool, nice job optimizing!

**Comment by TiarkRompf** [comment]
Out of curiosity, how long do solutions in other languages take?

**Comment by Sohaib03** [comment]
Hello. My solution in C++ takes on average 10ms. I have seen some people posting solutions in JS taking as low as 40ms.

**Comment by Sohaib03** [comment]
At line 2572, we have this:  
`
 let tuples = [
        ["*fD", "\"v\"", 0, -1],
        ["*fU", "\"^\"", 0,  1],
        ["*fR", "\">\"", -1, 0],
        ["*fL", "\"<\"",  1, 0],
    ];
`

There are no '^' and '<' directions in part 1 of the problem. I believe there should be only two elements in this tuple.

**Pull request merged**
