### PR TITLE
Developing versions of filters and AdventOfCode day3-part2 challenge

### PR DESCRIPTION
**Pull request by Kuigesi**

### CODE REVIEW

**Comment by TiarkRompf** [comment]
Thanks for trying this out and having a shot at implementing filters!

For comparison, I think I would like to see how AOC day 3 works with the alternative approach I prototyped in the "generatorAsFilter" test. Do you want to quickly try that as well?

Regarding the implementation in this PR in ir.js, the addition of 'preds' to every expression seems a bit heavy, so if we can do something like `deps.filter(isPred)` that would look preferable. Filters could be a special kind of variable, or, using the "generatorAsFilter" approach, they are just regular index variables.

As you mentioned, there is also some redundancy in checking predicates. If we treat filters (conceptually) as lookups in 0- or 1-element collections , then we can reuse most of the existing nesting logic from traversals, and perhaps get some additional benefits by hoisting generator that we know are in fact filters.

**Comment by Kuigesi** [comment]
> Thanks for trying this out and having a shot at implementing filters!
> 
> For comparison, I think I would like to see how AOC day 3 works with the alternative approach I prototyped in the "generatorAsFilter" test. Do you want to quickly try that as well?
> 
> Regarding the implementation in this PR in ir.js, the addition of 'preds' to every expression seems a bit heavy, so if we can do something like `deps.filter(isPred)` instead that would look preferable. Filters could be a special kind of variable, or, using the "generatorAsFilter" approach, they are just regular index variables.
> 
> As you mentioned, there is also some redundancy in checking predicates. If we treat filters (conceptually) as lookups in 0- or 1-element collections , then we can reuse most of the existing nesting logic from traversals, and perhaps get some additional benefits by hoisting generators that we know are in fact filters.

**Comment by Kuigesi** [comment]
> Thanks for trying this out and having a shot at implementing filters!
> 
> For comparison, I think I would like to see how AOC day 3 works with the alternative approach I prototyped in the "generatorAsFilter" test. Do you want to quickly try that as well?
> 
> Regarding the implementation in this PR in ir.js, the addition of 'preds' to every expression seems a bit heavy, so if we can do something like `deps.filter(isPred)` instead that would look preferable. Filters could be a special kind of variable, or, using the "generatorAsFilter" approach, they are just regular index variables.
> 
> As you mentioned, there is also some redundancy in checking predicates. If we treat filters (conceptually) as lookups in 0- or 1-element collections , then we can reuse most of the existing nesting logic from traversals, and perhaps get some additional benefits by hoisting generators that we know are in fact filters.

Thanks so much for the feedback, I will try the generatorAsFilter test!

**Comment by TiarkRompf** [comment]
This one also seems to be superseded by other work in the meantime.

**Pull request closed without merging**
